Resources:
  EcsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecs-fastapi-task-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ecs-fastapi-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Publish to SNS
              - Effect: Allow
                Action:
                  - sns:Publish
                  #sns --> arn
                Resource: "*"

              # Presigned URL S3 access
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: "arn:aws:s3:::your-bucket-name/*"

              # DynamoDB (documents table)
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                Resource: "*"

  AuditLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: audit-lambda-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: audit-lambda-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Read from SQS
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: "*"

              # Write to DynamoDB Audit table
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: "*"


  NotificationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: notification-lambda-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: notification-lambda-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Read from SQS
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: "*"

              # Send email via SES
              - Effect: Allow
                Action:
                  - ses:SendEmail
                  - ses:SendRawEmail
                Resource: "*"
