Resources:
  EcsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecs-fastapi-task-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ecs-fastapi-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: "arn:aws:sns:ap-south-1:386667539956:approvel"

              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: "arn:aws:s3:::my-doc-approval-bucket/*"

              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                Resource: "arn:aws:dynamodb:ap-south-1:386667539956:table/documentApprovel"

  AuditLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: audit-lambda-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: audit-lambda-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: "arn:aws:sqs:ap-south-1:386667539956:audit-queue"

              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: "arn:aws:dynamodb:ap-south-1:386667539956:table/documentApprovel"


  NotificationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: notification-lambda-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: notification-lambda-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: "arn:aws:sqs:ap-south-1:386667539956:notification-queue"

              - Effect: Allow
                Action:
                  - ses:SendEmail
                Resource: "*"
