AWSTemplateFormatVersion: '2010-09-09'

Resources:
  DocumentEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: document-events-topic

Outputs:
  DocumentEventsTopicArn:
    Description: SNS Topic ARN
    Value: !Ref DocumentEventsTopic
