AWSTemplateFormatVersion: '2010-09-09'

Resources:
  DocumentEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: document-events-topic

      Tags:
        - Key: Service
          Value: document-approval

Outputs:
  DocumentEventsTopicArn:
    Description: SNS Topic ARN
    Value: !Ref DocumentEventsTopic
